<a href="https://colab.research.google.com/github/7h310v3/Baitap/blob/main/Numpy_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Câu 1: Sử dụng thư viện Numpy, hãy tạo một vector a có 7 chiều (tương ứng 7 phần tử) với giá
trị các phần tử được sinh bằng hàm (kết quả xuất ra màn hình):
- np.arrange()
- np.linspace()
- np.logspace()
- np.random.rand()
Ghi chú: sau mỗi lần sinh ra giá trị cho vector, hãy cho biết số chiều của vector được sinh ra và
số chiều của vector chuyển vị của vector đó; cho biết kích thước của vector a và vector chuyển vị
của vector a.
Gợi ý: tham khảo ndim và shape.

In [7]:
import numpy as np

# Using arange() function
A = np.arange(1, 8, 1)
print("Arange function: ",A)

# Using linespace() function
B = np.linspace(1, 7, 7, dtype = int)
print("Linespace function: ", B)

# Using logspace() function
C = np.logspace(1, 2, 7, dtype = int)
print("Logspace function: ", C)

# Using random.rand() function
D = np.random.rand(1, 7)
print("Rand function: ", D)

Arange function:  [1 2 3 4 5 6 7]
Linespace function:  [1 2 3 4 5 6 7]
Logspace function:  [ 10  14  21  31  46  68 100]
Rand function:  [[0.97648179 0.27565768 0.09453841 0.76934048 0.32280822 0.32319359
  0.70847366]]


Câu 2: Sử dụng thư viện Numpy, hãy tạo ra ma trận A10x7 với giá trị các phần tử của ma trận A
được sinh bởi:
- np.arrange()
- np.linspace()
- np.logspace()
- np.random.rand()
Sau mỗi lần ma trận được tạo ra, hãy xuất kết quả ra màn hình và cho biết:
- Số chiều và kích thước của ma trận A và ma trận AT

In [8]:
A = np.arange(0,70).reshape(10,7)
print(A)
print("Số chiều của vectoer a: ",A.ndim)
print("Số chiều vector chuyển vị vector a: ",A.T.ndim)
print("Kích thước vector A: ",A.shape)
print("Kích thước vector chuyển vị vector A: ",A.T.shape)

B = np.linspace(0,7,70).reshape(10,7)
print (B)
print("Số chiều của vector B: ",B.ndim)
print("Số chiều vector chuyển vị vector B: ",B.T.ndim)
print("Kích thước vector B: ",B.shape)
print("Kích thước vector chuyển vị vector B: ",B.T.shape)

C = np.logspace(1, 2, num = 70).reshape(10,7)
print (C)
print("Số chiều của vector a: ",C.ndim)
print("Số chiều vector chuyển vị vector C: ",C.T.ndim)
print("Kích thước vector C: ",C.shape)
print("Kích thước vector chuyển vị vector C: ",C.T.shape)

D = np.random.rand(10,7)
print(D)
print("Số chiều của vector D: ",D.ndim)
print("Số chiều vector chuyển vị vector D: ",D.T.ndim)
print("Kích thước vector D: ",D.shape)
print("Kích thước vector chuyển vị vector D: ",D.T.shape)

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]
 [35 36 37 38 39 40 41]
 [42 43 44 45 46 47 48]
 [49 50 51 52 53 54 55]
 [56 57 58 59 60 61 62]
 [63 64 65 66 67 68 69]]
Số chiều của vectoer a:  2
Số chiều vector chuyển vị vector a:  2
Kích thước vector A:  (10, 7)
Kích thước vector chuyển vị vector A:  (7, 10)
[[0.         0.10144928 0.20289855 0.30434783 0.4057971  0.50724638
  0.60869565]
 [0.71014493 0.8115942  0.91304348 1.01449275 1.11594203 1.2173913
  1.31884058]
 [1.42028986 1.52173913 1.62318841 1.72463768 1.82608696 1.92753623
  2.02898551]
 [2.13043478 2.23188406 2.33333333 2.43478261 2.53623188 2.63768116
  2.73913043]
 [2.84057971 2.94202899 3.04347826 3.14492754 3.24637681 3.34782609
  3.44927536]
 [3.55072464 3.65217391 3.75362319 3.85507246 3.95652174 4.05797101
  4.15942029]
 [4.26086957 4.36231884 4.46376812 4.56521739 4.66666667 4.76811594
  4.86956522]
 [4.97101449 5.07246377 5.17391304 5.275362

Câu 3: Sử dụng thư viện Numpy, hãy:
- Chuyển ma trận A ở câu 2 thành vector. (Gợi ý: sử dụng hàm flatten())
- Chuyển vector vừa được tạo ra ở câu trên thành ma trận. (Gợi ý: sử dụng hàm reshape())

In [11]:
#3
print("Vector A: \n", A.flatten())
print("Vector B: \n", B.flatten())
print("Vector C: \n", C.flatten())
print("Vector D: \n", D.flatten())

print("Ma trận A: \n", A.reshape(10,7))
print("Ma trận B: \n", B.reshape(10,7))
print("Ma trận C: \n", C.reshape(10,7))
print("Ma trận S: \n", D.reshape(10,7))


Vector A: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69]
Vector B: 
 [0.         0.10144928 0.20289855 0.30434783 0.4057971  0.50724638
 0.60869565 0.71014493 0.8115942  0.91304348 1.01449275 1.11594203
 1.2173913  1.31884058 1.42028986 1.52173913 1.62318841 1.72463768
 1.82608696 1.92753623 2.02898551 2.13043478 2.23188406 2.33333333
 2.43478261 2.53623188 2.63768116 2.73913043 2.84057971 2.94202899
 3.04347826 3.14492754 3.24637681 3.34782609 3.44927536 3.55072464
 3.65217391 3.75362319 3.85507246 3.95652174 4.05797101 4.15942029
 4.26086957 4.36231884 4.46376812 4.56521739 4.66666667 4.76811594
 4.86956522 4.97101449 5.07246377 5.17391304 5.27536232 5.37681159
 5.47826087 5.57971014 5.68115942 5.7826087  5.88405797 5.98550725
 6.08695652 6.1884058  6.28985507 6.39130435 6.49275362 6.5942029
 6.69565217 6.79710145 6.8

Câu 4: Sử dụng thư viện Numpy, hãy:
- Tạo ra 1 ma trận A10x15 với các giá trị được sinh ra bởi hàm logspace();
- Hãy trích rút dòng thứ 3 của ma trận A (tương ứng với 1 vector hàng);
- Hãy trích rút ra cột thứ 5 của ma trận A (tương ứng với 1 vector cột).

In [14]:
#4
A = np.logspace(1, 2, num = 150).reshape(10,15)
print (A)
print("Hàng thứ 3 của ma trận A:\n", A[2])
print("Cột thứ 5 của ma trận A:\n", A[:,4:5])


[[ 10.          10.15573615  10.31389768  10.47452236  10.63764854
   10.80331519  10.97156187  11.14242875  11.31595665  11.49218701
   11.67116191  11.8529241   12.03751698  12.22498464  12.41537185]
 [ 12.60872408  12.8050875   13.00450901  13.20703623  13.41271753
   13.62160204  13.83373963  14.04918097  14.26797751  14.4901815
   14.71584602  14.94502495  15.17777302  15.41414582  15.6541998 ]
 [ 15.89799228  16.1455815   16.39702658  16.65238757  16.91172545
   17.17510215  17.44258059  17.71422463  17.99009916  18.27027004
   18.5548042   18.84376959  19.13723521  19.43527115  19.73794859]
 [ 20.04533981  20.35751822  20.67455838  20.996536    21.32352798
   21.65561241  21.99286859  22.33537706  22.68321964  23.03647938
   23.39524065  23.75958913  24.12961183  24.50539713  24.88703476]
 [ 25.27461587  25.66823302  26.06798021  26.4739529   26.88624807
   27.30496415  27.73020117  28.16206065  28.60064576  29.04606122
   29.4984134   29.95781035  30.42436177  30.89817908  31.3

Câu 5: Thực hiện các yêu cầu sau:
- Xây dựng hàm tính giá trị trung bình
- Xây dựng hàm tính giá trị trung vị
- Xây dựng hàm tính giá trị yếu vị
- Xây dựng hàm tính phương sai
- Xây dựng hàm tính độ lệch chuẩn
- Hãy tạo ra ma trận A15x10 với các giá trị sinh bởi hàm arrange()
- Áp dụng 5 hàm ở trên cho từng hàng của ma trận A
- Áp dụng 5 hàm ở trên cho từng cột của ma trận A
Gợi ý: tham khảo hàm apply_along_axis() đã học ở bài trước.

In [5]:
#5
A = np.arange(1,151).reshape(15,10)
print(A, "\n")

print("Giá trị trung bình từng hàng của A = \n", np.apply_along_axis(np.mean, 1, A))
print("Giá trị trung bình từng cột của A = \n", np.apply_along_axis(np.mean, 0, A))

print("Giá trị trung vị từng hàng của A = \n", np.apply_along_axis(np.median, 1, A))
print("Giá trị trung vị từng cột của A = \n", np.apply_along_axis(np.median, 0, A))

print("Phương sai từng hàng của A = \n", np.apply_along_axis(np.var, 1, A))
print("Phương sai từng cột của A = \n", np.apply_along_axis(np.var, 0, A))

print("Độ lệch chuẩn từng hàng của A = \n", np.apply_along_axis(np.std, 1, A))
print("Độ lệch chuẩn từng cột của A = \n", np.apply_along_axis(np.std, 0, A))



[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]
 [101 102 103 104 105 106 107 108 109 110]
 [111 112 113 114 115 116 117 118 119 120]
 [121 122 123 124 125 126 127 128 129 130]
 [131 132 133 134 135 136 137 138 139 140]
 [141 142 143 144 145 146 147 148 149 150]] 

Giá trị trung bình từng hàng của A = 
 [  5.5  15.5  25.5  35.5  45.5  55.5  65.5  75.5  85.5  95.5 105.5 115.5
 125.5 135.5 145.5]
Giá trị trung bình từng cột của A = 
 [71. 72. 73. 74. 75. 76. 77. 78. 79. 80.]
Giá trị trung vị từng hàng của A = 
 [  5.5  15.5  25.5  35.5  45.5  55.5  65.5  75.5  85.5  95.5 105.5 115.5
 125.5 135.5 145.5]
Giá trị tr